"""add disciplines, associates and complete users

Revision ID: 208fd553879e
Revises: c9df50cb3f85
Create Date: 2022-09-21 20:27:55.601001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208fd553879e'
down_revision = 'c9df50cb3f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associates',
    sa.Column('associate_number', sa.Integer(), nullable=False),
    sa.Column('DNI_number', sa.Integer(), nullable=True),
    sa.Column('DNI_type', sa.Enum('DNI', 'LE', 'LC', name='dnioptions'), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='genderoptions'), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('associate_number'),
    sa.UniqueConstraint('DNI_number')
    )
    op.create_table('disciplines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('instructors', sa.String(length=255), nullable=True),
    sa.Column('dates', sa.String(length=255), nullable=True),
    sa.Column('monthly_cost', sa.Numeric(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'active')
    op.drop_table('disciplines')
    op.drop_table('associates')
    # ### end Alembic commands ###
