from grupo12.admin.src.core.board.associate import Associate

#here is where CRUD are made
#QUESTION TO ASK TO GROUP, shall we do it in a CLASS or in different functions?
def get_associate_by_id(associate_number):
    """ Get associate by id
    Args:
        - associate_number (integer): Associate number. Unique, autogenerated
    Returns:
        - Associate object
    """
    return Associate.query.get(associate_number)

def list_associates():
    """ List all associates
    Returns:
        - List of Associate objects
    """
    return Associate.query.all()