from src.core.board.associate import Associate
from src.core.board import associates
from src.web.helpers.form_utils import bool_checker, csrf_remover



def get_associate_by_id(id):
    """ Get associate by id
    Args:
        - id (integer): Associate number. Unique, autogenerated
    Returns:
        - Associate object
    """
    return associates.get(id)

def get_associate_by_DNI(DNI_number):
    """ Get associate by DNI
    Args:
        - DNI_number (integer): Associate DNI number
    Returns:
        - Associate object
    """
    return associates.query.filter(Associate.DNI_number == DNI_number).first()

def list_associates(column=None,filter=True):
    """ List all associates
    Returns:
        - List of Associate objects
    """
    if column:
        return associates.paginated_filter(column,filter)
    return associates.paginated_list()

def create_associate(form_data):
    """ Create associate
    Returns:
        - Create associate
    """
    associate = Associate(**form_data)
    associates.add(associate)
    return associate

def update_associate(form_data,id):
    """ Update associate
    Returns:
        - Update associate
    """
    associate_data = csrf_remover(form_data)
    associate_data.update(active=bool_checker(form_data["active"]))
    associates.update(id,associate_data)

def delete_associate(id):
    """Delete associate
    Returns:
        - Delete associate
    """
    associates.delete(id)
    

def disable_associate(id):
    """Disable associate
    Returns:
        - Disabled associate
    """
    associates.update(id,{"active":False})
    
def enable_associate(id):
    """Enable associate
    Returns:
        - Enabled associate
    """
    associates.update(id,{"active":True})
    
