from src.core.board.associate import Associate
from src.core.board import associates



def get_associate_by_id(associate_number):
    """ Get associate by id
    Args:
        - associate_number (integer): Associate number. Unique, autogenerated
    Returns:
        - Associate object
    """
    return associates.get(associate_number)

def get_associate_by_DNI(DNI_number):
    """ Get associate by DNI
    Args:
        - DNI_number (integer): Associate DNI number
    Returns:
        - Associate object
    """
    return associates.query.filter(Associate.DNI_number == DNI_number).first()

def list_associates():
    """ List all associates
    Returns:
        - List of Associate objects
    """
    return associates.list()

def create_associate(form_data):
    """ Create associate
    Returns:
        - Create associate
    """
    associate = Associate(**form_data)
    associates.add(associate)
    return associate

def update_associate(form_data,id):
    """ Update associate
    Returns:
        - Update associate
    """
    associates.update(id,form_data)

def delete_associate(id):
    """Delete associate
    Returns:
        - Delete associate
    """
    associates.delete(id)
    

def disable_associate(id):
    """Disable associate
    Returns:
        - Disabled associate
    """
    associates.update(id,{"active":False})
    
def enable_associate(id):
    """Enable associate
    Returns:
        - Enabled associate
    """
    associates.update(id,{"active":True})
    
