from src.core.auth.user import User
from src.core.db import db

def get_user_by_id(user_id):
    """ Get user by id
    Args:
        - user_id (integer): User id. Unique, autogenerated
    Returns:
        - User object
    """
    return User.query.get(user_id)

def list_users():
    """ List all users
    Returns:
        - List of User objects
    """
    return User.query.all()

def create_user(form):
    """ Create user
    Returns:
        - Create user
    """
    user = User(**form.data)
    db.session.add(user)
    db.session.commit()
    return user

def delete_user(user_id):
    """ Delete user
    Returns:
        - Delete user
    """
    db.session.query(User).filter(User.id == user_id).delete()
    db.session.commit()

def update_user(user_id, form):
    """ Update user
    Returns:
        - Update user
    """
    user = get_user_by_id(user_id)
    user.username = form.username.data
    user.password = form.password.data
    user.email = form.email.data
    user.first_name = form.first_name.data
    user.last_name = form.last_name.data
    db.session.commit()
    return user